import json
import os

cells = []

# Cell 0: Header & Detailed Introduction (Markdown)
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "header_md"},
    "source": [
        "# 1. Decoder-Only Autoregressive Graph Shortest Path Transformer\n",
        "## Causal Language Modeling Mechanics over Hardened Algorithmic Traversal Traces\n",
        "\n",
        "### Executive Summary & Educational Motivation\n",
        "Extracting structural path information from complex, noisy algorithmic execution traces is a fundamental challenge in neural algorithmic reasoning. Standard sequence-to-sequence models utilize an **Encoder-Decoder** architecture, where an encoder processes the input trace $T = [t_1, t_2, \\dots, t_K]$ and a decoder cross-attends to the encoded representations while generating target path tokens $P^* = [p_1^*, p_2^*, \\dots, p_M^*]$.\n",
        "\n",
        "In this notebook, we reformulate graph shortest path extraction using a **Decoder-Only Transformer**, mirroring the architecture of modern Large Language Models (LLMs) such as GPT-4, LLaMA, and DeepSeek. In a decoder-only setup, the input execution trace and target path sequence are concatenated into a single unified sequence:\n",
        "$$X = [t_1, t_2, \\dots, t_K, p_1^*, p_2^*, \\dots, p_M^*, \\text{STOP_TOKEN}]$$\n",
        "\n",
        "The model processes this sequence using strictly **Causal Self-Attention**, where every position can only attend to preceding tokens ($j \\le i$). Cross-attention is completely eliminated. Training leverages next-token prediction with selective loss masking, ignoring loss on the input trace prompt tokens and computing loss strictly over the target path rollout.\n",
        "\n",
        "---\n",
        "\n",
        "### Mathematical Problem Formulation\n",
        "\n",
        "#### 1. Unified Sequence Representation\n",
        "Given an input Depth-First Search (DFS) trace $T = [t_1, t_2, \\dots, t_K]$ ($30 \\le K \\le 50$) where $t_1 = s$ and $t_K = g$, and ground-truth shortest path $P^* = [p_1^*, p_2^*, \\dots, p_M^*]$ ($10 \\le M \\le 20$), the sequence is concatenated into:\n",
        "$$X = [t_1, t_2, \\dots, t_K, p_1^*, p_2^*, \\dots, p_M^*, \\text{STOP}]$$\n",
        "\n",
        "#### 2. Causal Masking & Next-Token Prediction\n",
        "The input sequence $X_{\\text{in}} = X[:-1]$ is mapped to token embeddings and sinusoidal positional encodings:\n",
        "$$H_0 = \\text{Embedding}(X_{\\text{in}}) + \\text{PositionalEncoding}(X_{\\text{in}}) \\in \\mathbb{R}^{L \\times d_{\\text{model}}}$$\n",
        "\n",
        "The causal transformer applies $N$ layers of Causal Self-Attention with lower-triangular causal mask $M_{\\text{causal}}$:\n",
        "$$M_{\\text{causal}}[i, j] = \\begin{cases} 0 & \\text{if } i \\ge j \\\\ -\\infty & \\text{if } i < j \\end{cases}$$\n",
        "$$H_l = \\text{CausalTransformerBlock}(H_{l-1}, M_{\\text{causal}})$$\n",
        "$$Z = \\text{Linear}(H_N) \\in \\mathbb{R}^{L \\times V}$$\n",
        "\n",
        "#### 3. Selective Loss Masking\n",
        "Cross-entropy loss is computed against target labels $Y = X[1:]$. To focus optimization exclusively on shortest path extraction, loss is masked out for trace prompt positions ($i < K-1$):\n",
        "$$\\mathcal{L} = -\\frac{1}{\\sum m_i} \\sum_{i=K-1}^{L-1} \\log P(Y_i \\mid X_{\\le i})$$\n",
        "where $m_i = 1$ for path target tokens and $0$ for trace prompt and padding tokens.\n",
        "\n",
        "#### 4. Autoregressive Rollout & Compounding Errors\n",
        "During inference (`solve_graph_autoregressive`), the model is prompted with trace $T = [t_1, \\dots, t_K]$. It iteratively samples next path tokens $p_m$ conditioned on $[T, p_1, \\dots, p_{m-1}]$ until generating `STOP_TOKEN`. Early prediction errors shift the causal decoder state out-of-distribution, scaling exact match failure rate as $1 - (1 - \\epsilon)^M$.\n"
    ]
})

# Cell 1: Environment Setup, Seeds, and Google Drive Configuration (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_1",
    "metadata": {"id": "cell_1"},
    "outputs": [],
    "source": [
        "# Cell 1: Environment Setup, Seeds, and Google Drive Configuration\n",
        "\n",
        "import os\n",
        "import random\n",
        "import time\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.nn.functional as F\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import networkx as nx\n",
        "\n",
        "# Ensure directories exist relative to CWD\n",
        "if os.path.basename(os.getcwd()) == \"graphs\":\n",
        "    os.makedirs(\"../charts\", exist_ok=True)\n",
        "    os.makedirs(\"charts\", exist_ok=True)\n",
        "    os.makedirs(\"checkpoints\", exist_ok=True)\n",
        "    LOCAL_DATA_PATH = \"data/graph_dfs_dataset.pt\"\n",
        "    LOCAL_CKPT_DIR = \"checkpoints\"\n",
        "else:\n",
        "    os.makedirs(\"charts\", exist_ok=True)\n",
        "    os.makedirs(\"graphs/charts\", exist_ok=True)\n",
        "    os.makedirs(\"graphs/checkpoints\", exist_ok=True)\n",
        "    LOCAL_DATA_PATH = \"src/static/data/graph_dfs_dataset.pt\"\n",
        "    LOCAL_CKPT_DIR = \"graphs/checkpoints\"\n",
        "\n",
        "torch.set_num_threads(1)\n",
        "\n",
        "def set_seed(seed=42):\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    if torch.cuda.is_available():\n",
        "        torch.cuda.manual_seed_all(seed)\n",
        "\n",
        "set_seed(42)\n",
        "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "\n",
        "# Google Drive Mount & Path Resolution\n",
        "def setup_drive_paths():\n",
        "    try:\n",
        "        from google.colab import drive\n",
        "        drive.mount('/content/drive')\n",
        "        data_path = \"/content/drive/MyDrive/graph_data/graph_dfs_dataset.pt\"\n",
        "        ckpt_dir = \"/content/drive/MyDrive/graph_checkpoints\"\n",
        "    except ImportError:\n",
        "        data_path = LOCAL_DATA_PATH\n",
        "        ckpt_dir = LOCAL_CKPT_DIR\n",
        "\n",
        "    os.makedirs(ckpt_dir, exist_ok=True)\n",
        "    print(f\"Dataset path: {data_path}\")\n",
        "    print(f\"Checkpoints path: {ckpt_dir}\")\n",
        "    return data_path, ckpt_dir\n",
        "\n",
        "DATASET_PATH, CKPT_DIR = setup_drive_paths()\n"
    ]
})

# Cell 2 Header: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_2_md"},
    "source": [
        "### Causal Dataset Processing & PyTorch Dataset Class\n",
        "Loads the pre-generated DFS dataset ($30 \\le K \\le 50$, $10 \\le M \\le 20$).\n",
        "- `trace`: Input 1D DFS trace of length $K$.\n",
        "- `sp`: Ground-truth shortest path of length $M$.\n",
        "- Concatenates sequence into `[trace + sp + STOP_TOKEN]` padded to `MAX_COMBINED_LEN = 71` (`MAX_SRC_LEN=50` + `MAX_TGT_LEN=21`).\n",
        "- Masks target label loss for input trace positions ($i < K-1$), ensuring the loss gradient is applied strictly to next-token predictions on the target path.\n"
    ]
})

# Cell 2: Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_2",
    "metadata": {"id": "cell_2"},
    "outputs": [],
    "source": [
        "# Cell 2: Import Hardened Dataset & Define PyTorch Causal Dataset\n",
        "\n",
        "search_paths = [\n",
        "    DATASET_PATH,\n",
        "    \"data/graph_dfs_dataset.pt\",\n",
        "    \"graphs/data/graph_dfs_dataset.pt\",\n",
        "    \"src/static/data/graph_dfs_dataset.pt\"\n",
        "]\n",
        "\n",
        "actual_dataset_path = None\n",
        "for path in search_paths:\n",
        "    if os.path.exists(path):\n",
        "        actual_dataset_path = path\n",
        "        break\n",
        "\n",
        "if actual_dataset_path is None:\n",
        "    raise FileNotFoundError(f\"Dataset file not found in search paths: {search_paths}.\")\n",
        "\n",
        "dataset_payload = torch.load(actual_dataset_path, weights_only=False)\n",
        "train_raw = dataset_payload['train']\n",
        "val_raw = dataset_payload['val']\n",
        "test_raw = dataset_payload['test']\n",
        "\n",
        "VOCAB_SIZE = dataset_payload.get('vocab_size', 42)\n",
        "PAD_TOKEN = dataset_payload.get('pad_token', 40)\n",
        "STOP_TOKEN = dataset_payload.get('stop_token', 41)\n",
        "MAX_SRC_LEN = dataset_payload.get('max_src_len', 50)\n",
        "MAX_TGT_LEN = dataset_payload.get('max_tgt_len', 21)\n",
        "MAX_COMBINED_LEN = MAX_SRC_LEN + MAX_TGT_LEN\n",
        "\n",
        "class GraphDFSDecoderOnlyDataset(Dataset):\n",
        "    def __init__(self, raw_data, max_combined_len=MAX_COMBINED_LEN):\n",
        "        self.samples = []\n",
        "        self.raw_data = raw_data\n",
        "        for item in raw_data:\n",
        "            trace, sp, G, mapping = item[0], item[1], item[2], item[3]\n",
        "            backtracks = item[4] if len(item) > 4 else 0\n",
        "            node_backtraces = item[5] if len(item) > 5 else {}\n",
        "\n",
        "            K = len(trace)\n",
        "            tgt_seq = list(sp) + [STOP_TOKEN]\n",
        "            full_seq = list(trace) + tgt_seq\n",
        "            pad_len = max_combined_len - len(full_seq)\n",
        "            full_seq_padded = full_seq + [PAD_TOKEN] * pad_len\n",
        "\n",
        "            # Causal Sequence: Input = X[:-1], Target = X[1:]\n",
        "            inp = full_seq_padded[:-1]\n",
        "            lbl = list(full_seq_padded[1:])\n",
        "\n",
        "            # Mask out loss on input trace prompt tokens (positions 0 to K-2)\n",
        "            for idx in range(K - 1):\n",
        "                lbl[idx] = PAD_TOKEN\n",
        "\n",
        "            inp_mask = [t == PAD_TOKEN for t in inp]\n",
        "\n",
        "            self.samples.append((\n",
        "                torch.tensor(inp, dtype=torch.long),\n",
        "                torch.tensor(lbl, dtype=torch.long),\n",
        "                torch.tensor(inp_mask, dtype=torch.bool),\n",
        "                trace,\n",
        "                sp,\n",
        "                G,\n",
        "                backtracks,\n",
        "                node_backtraces\n",
        "            ))\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.samples)\n",
        "\n",
        "    def __getitem__(self, idx):\n",
        "        return self.samples[idx]\n",
        "\n",
        "def graph_decoder_only_collate_fn(batch):\n",
        "    inp = torch.stack([item[0] for item in batch])\n",
        "    lbl = torch.stack([item[1] for item in batch])\n",
        "    inp_mask = torch.stack([item[2] for item in batch])\n",
        "    traces = [item[3] for item in batch]\n",
        "    sps = [item[4] for item in batch]\n",
        "    graphs = [item[5] for item in batch]\n",
        "    backtracks = [item[6] for item in batch]\n",
        "    node_backtraces = [item[7] for item in batch]\n",
        "    return inp, lbl, inp_mask, traces, sps, graphs, backtracks, node_backtraces\n",
        "\n",
        "train_dataset = GraphDFSDecoderOnlyDataset(train_raw)\n",
        "val_dataset = GraphDFSDecoderOnlyDataset(val_raw)\n",
        "test_dataset = GraphDFSDecoderOnlyDataset(test_raw)\n",
        "\n",
        "train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, collate_fn=graph_decoder_only_collate_fn)\n",
        "val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False, collate_fn=graph_decoder_only_collate_fn)\n",
        "test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False, collate_fn=graph_decoder_only_collate_fn)\n",
        "\n",
        "print(f\"Decoder-Only Datasets loaded successfully: Train={len(train_dataset)}, Val={len(val_dataset)}, Test={len(test_dataset)}\")\n"
    ]
})

# Cell 3 Header: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_3_md"},
    "source": [
        "### Decoder-Only Graph Shortest Path Transformer Architecture\n",
        "Implements a **Causal Decoder-Only Transformer** (as in traditional LLMs):\n",
        "1. **Token Embedding & Sinusoidal Positional Encoding**: Embeds node IDs and control tokens into $d_{\\text{model}} = 16$.\n",
        "2. **Causal Transformer Stack**: $N=4$ Transformer Encoder Layers with boolean lower-triangular causal self-attention mask (`is_causal`).\n",
        "3. **Linear Output Projection**: Projects hidden representations $h_i \\in \\mathbb{R}^{16}$ to vocabulary logits $\\in \\mathbb{R}^{42}$.\n",
        "4. **Unguided Autoregressive Rollout (`solve_graph_autoregressive`)**: Accepts raw 1D trace prompt $T = [t_1, \\dots, t_K]$, evaluates causal attention over prompt, and iteratively appends predicted path tokens until `STOP_TOKEN` or `max_tgt_len` is reached.\n"
    ]
})

# Cell 3: Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_3",
    "metadata": {"id": "cell_3"},
    "outputs": [],
    "source": [
        "# Cell 3: Model Architecture Definition (Decoder-Only Causal Transformer)\n",
        "\n",
        "class PositionalEncoding(nn.Module):\n",
        "    def __init__(self, d_model, max_len=150):\n",
        "        super(PositionalEncoding, self).__init__()\n",
        "        pe = torch.zeros(max_len, d_model)\n",
        "        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)\n",
        "        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-np.log(10000.0) / d_model))\n",
        "        pe[:, 0::2] = torch.sin(position * div_term)\n",
        "        pe[:, 1::2] = torch.cos(position * div_term)\n",
        "        self.register_buffer('pe', pe.unsqueeze(0))\n",
        "\n",
        "    def forward(self, x):\n",
        "        return x + self.pe[:, :x.size(1)]\n",
        "\n",
        "class DecoderOnlyGraphTransformer(nn.Module):\n",
        "    def __init__(self, vocab_size=VOCAB_SIZE, embed_dim=16, num_heads=2, hidden_dim=32, num_layers=4):\n",
        "        super(DecoderOnlyGraphTransformer, self).__init__()\n",
        "        self.embed_dim = embed_dim\n",
        "        self.token_embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=PAD_TOKEN)\n",
        "        self.pos_encoder = PositionalEncoding(embed_dim, max_len=150)\n",
        "\n",
        "        decoder_layer = nn.TransformerEncoderLayer(\n",
        "            d_model=embed_dim,\n",
        "            nhead=num_heads,\n",
        "            dim_feedforward=hidden_dim,\n",
        "            dropout=0.1,\n",
        "            activation='gelu',\n",
        "            batch_first=True\n",
        "        )\n",
        "        self.transformer = nn.TransformerEncoder(decoder_layer, num_layers=num_layers)\n",
        "        self.fc_out = nn.Linear(embed_dim, vocab_size)\n",
        "\n",
        "    def generate_square_subsequent_mask(self, sz, device):\n",
        "        mask = torch.triu(torch.ones(sz, sz, device=device, dtype=torch.bool), diagonal=1)\n",
        "        return mask\n",
        "\n",
        "    def forward(self, x, padding_mask=None, causal_mask=None):\n",
        "        x_emb = self.pos_encoder(self.token_embedding(x))\n",
        "        out = self.transformer(x_emb, mask=causal_mask, src_key_padding_mask=padding_mask)\n",
        "        logits = self.fc_out(out)\n",
        "        return logits\n",
        "\n",
        "    def solve_graph_autoregressive(self, traces, max_tgt_len=MAX_TGT_LEN, device='cpu'):\n",
        "        self.eval()\n",
        "        batch_size = len(traces)\n",
        "        \n",
        "        # Start sequence with input trace prompt\n",
        "        curr_seqs = [list(tr) for tr in traces]\n",
        "        generated_paths = [[] for _ in range(batch_size)]\n",
        "        finished = [False] * batch_size\n",
        "\n",
        "        for step in range(max_tgt_len - 1):\n",
        "            if all(finished):\n",
        "                break\n",
        "\n",
        "            curr_max_len = max(len(s) for s in curr_seqs)\n",
        "            inp = torch.full((batch_size, curr_max_len), PAD_TOKEN, dtype=torch.long, device=device)\n",
        "            inp_mask = torch.zeros((batch_size, curr_max_len), dtype=torch.bool, device=device)\n",
        "\n",
        "            for b in range(batch_size):\n",
        "                s = curr_seqs[b]\n",
        "                inp[b, :len(s)] = torch.tensor(s, dtype=torch.long, device=device)\n",
        "                inp_mask[b, len(s):] = True\n",
        "\n",
        "            causal_mask = self.generate_square_subsequent_mask(curr_max_len, device)\n",
        "            logits = self.forward(inp, padding_mask=inp_mask, causal_mask=causal_mask)\n",
        "\n",
        "            for b in range(batch_size):\n",
        "                if finished[b]:\n",
        "                    continue\n",
        "                last_idx = len(curr_seqs[b]) - 1\n",
        "                next_tok = torch.argmax(logits[b, last_idx, :]).item()\n",
        "                if next_tok in (STOP_TOKEN, PAD_TOKEN):\n",
        "                    finished[b] = True\n",
        "                else:\n",
        "                    curr_seqs[b].append(next_tok)\n",
        "                    generated_paths[b].append(next_tok)\n",
        "\n",
        "        return generated_paths\n",
        "\n",
        "model = DecoderOnlyGraphTransformer().to(device)\n",
        "total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
        "print(f\"DecoderOnlyGraphTransformer initialized. Total Parameters: {total_params:,}\")\n"
    ]
})

# Cell 4 Header: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_4_md"},
    "source": [
        "### Evaluation Helper Functions\n",
        "Calculates:\n",
        "1. Teacher-Forcing Cross-Entropy Loss & Token Accuracy over target path tokens.\n",
        "2. Step-by-Step Rollout Exact Path Match (%).\n",
        "3. Valid Graph Connectivity (%).\n"
    ]
})

# Cell 4: Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_4",
    "metadata": {"id": "cell_4"},
    "outputs": [],
    "source": [
        "# Cell 4: Evaluation Helper Functions\n",
        "\n",
        "criterion = nn.CrossEntropyLoss(ignore_index=PAD_TOKEN)\n",
        "\n",
        "def evaluate_model(model, dataloader, device, run_rollout=True):\n",
        "    model.eval()\n",
        "    total_loss = 0.0\n",
        "    total_tf_tokens = 0\n",
        "    correct_tf_tokens = 0\n",
        "\n",
        "    exact_matches = 0\n",
        "    total_sequences = 0\n",
        "    valid_paths = 0\n",
        "\n",
        "    with torch.no_grad():\n",
        "        for inp, lbl, inp_mask, traces, sps, graphs, backtracks, node_backtraces in dataloader:\n",
        "            inp, lbl = inp.to(device), lbl.to(device)\n",
        "            inp_mask = inp_mask.to(device)\n",
        "\n",
        "            sz = inp.size(1)\n",
        "            causal_mask = model.generate_square_subsequent_mask(sz, device)\n",
        "\n",
        "            logits = model(inp, padding_mask=inp_mask, causal_mask=causal_mask)\n",
        "\n",
        "            loss = criterion(logits.reshape(-1, VOCAB_SIZE), lbl.reshape(-1))\n",
        "            total_loss += loss.item() * inp.size(0)\n",
        "\n",
        "            preds_tf = torch.argmax(logits, dim=-1)\n",
        "            valid_tokens = (lbl != PAD_TOKEN)\n",
        "            correct_tf_tokens += ((preds_tf == lbl) & valid_tokens).sum().item()\n",
        "            total_tf_tokens += valid_tokens.sum().item()\n",
        "\n",
        "            if run_rollout:\n",
        "                pred_seqs = model.solve_graph_autoregressive(traces, device=device)\n",
        "\n",
        "                for i in range(len(traces)):\n",
        "                    total_sequences += 1\n",
        "                    clean_pred = pred_seqs[i]\n",
        "                    clean_tgt = list(sps[i])\n",
        "\n",
        "                    if clean_pred == clean_tgt:\n",
        "                        exact_matches += 1\n",
        "\n",
        "                    G_eval = graphs[i]\n",
        "                    if len(clean_pred) >= 2 and clean_pred[0] == clean_tgt[0] and clean_pred[-1] == clean_tgt[-1]:\n",
        "                        is_valid = True\n",
        "                        for k in range(len(clean_pred) - 1):\n",
        "                            u, v = clean_pred[k], clean_pred[k+1]\n",
        "                            if not G_eval.has_edge(u, v):\n",
        "                                is_valid = False\n",
        "                                break\n",
        "                        if is_valid:\n",
        "                            valid_paths += 1\n",
        "\n",
        "    mean_loss = total_loss / len(dataloader.dataset)\n",
        "    tf_acc = (correct_tf_tokens / max(1, total_tf_tokens)) * 100.0\n",
        "    exact_match_acc = (exact_matches / max(1, total_sequences)) * 100.0 if run_rollout else 0.0\n",
        "    path_validity_acc = (valid_paths / max(1, total_sequences)) * 100.0 if run_rollout else 0.0\n",
        "\n",
        "    return mean_loss, tf_acc, exact_match_acc, path_validity_acc\n",
        "\n",
        "print(\"Evaluation helper functions initialized.\")\n"
    ]
})

# Cell 5 Header: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_5_md"},
    "source": [
        "### Configurable Training Loop with Restart & Full-Training Support\n",
        "The `config` dictionary includes explicit controls:\n",
        "- `restart_training`: When `True`, skips loading previous checkpoints and starts fresh from epoch 1.\n",
        "- `run_full_training`: When `True`, skips the `epochs_to_train` constraint and trains for the full `total_epochs` (e.g., 20 epochs).\n",
        "- `resume_training`: When `True` (and `restart_training` is `False`), automatically resumes from the latest checkpoint.\n",
        "- `validate_every`: Validation runs **strictly every 10 epochs**.\n"
    ]
})

# Cell 5: Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_5",
    "metadata": {"id": "cell_5"},
    "outputs": [],
    "source": [
        "# Cell 5: Training Loop with Config Controls\n",
        "\n",
        "config = {\n",
        "    \"restart_training\": True,   # Set to True to skip existing checkpoints and start fresh\n",
        "    \"run_full_training\": True,  # Set to True to train for total_epochs ignoring epochs_to_train\n",
        "    \"resume_training\": True,    # Resumes from latest checkpoint if restart_training is False\n",
        "    \"total_epochs\": 20,\n",
        "    \"save_every\": 10,\n",
        "    \"validate_every\": 10,\n",
        "    \"epochs_to_train\": 20,      # Interactive execution chunk size\n",
        "    \"learning_rate\": 1e-3,\n",
        "    \"batch_size\": 64\n",
        "}\n",
        "\n",
        "latest_ckpt_path = os.path.join(CKPT_DIR, \"decoder_only_ar_graph_transformer_latest.pt\")\n",
        "optimizer = torch.optim.AdamW(model.parameters(), lr=config[\"learning_rate\"], weight_decay=1e-4)\n",
        "\n",
        "start_epoch = 1\n",
        "history = {\n",
        "    'train_loss': [],\n",
        "    'val_epochs': [],\n",
        "    'val_loss': [],\n",
        "    'val_tf_acc': [],\n",
        "    'val_exact_match': [],\n",
        "    'val_path_validity': []\n",
        "}\n",
        "\n",
        "# Handle restart_training and resume_training configuration\n",
        "if config.get(\"restart_training\", False):\n",
        "    print(\"Config 'restart_training' is True: Fresh initialization, skipping checkpoint loading.\")\n",
        "    start_epoch = 1\n",
        "elif config.get(\"resume_training\", True) and os.path.exists(latest_ckpt_path):\n",
        "    try:\n",
        "        print(f\"Loading checkpoint from '{latest_ckpt_path}'...\")\n",
        "        checkpoint = torch.load(latest_ckpt_path, map_location=device, weights_only=False)\n",
        "        model.load_state_dict(checkpoint['model_state_dict'])\n",
        "        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])\n",
        "        start_epoch = checkpoint['epoch'] + 1\n",
        "        if 'history' in checkpoint:\n",
        "            history = checkpoint['history']\n",
        "        print(f\"Resumed training from epoch {start_epoch}.\")\n",
        "    except Exception as e:\n",
        "        print(f\"Checkpoint incompatible ({e}). Starting fresh training from epoch 1...\")\n",
        "        start_epoch = 1\n",
        "else:\n",
        "    print(\"Starting training from scratch...\")\n",
        "\n",
        "# Determine end epoch based on run_full_training\n",
        "if config.get(\"run_full_training\", False):\n",
        "    end_epoch = config[\"total_epochs\"]\n",
        "    print(f\"Config 'run_full_training' is True: Running full training up to {end_epoch} epochs.\")\n",
        "else:\n",
        "    end_epoch = min(start_epoch + config[\"epochs_to_train\"] - 1, config[\"total_epochs\"])\n",
        "    print(f\"Running training chunk: epochs {start_epoch} to {end_epoch} (Config Total Target: {config['total_epochs']} epochs)...\")\n",
        "\n",
        "start_train_time = time.time()\n",
        "\n",
        "for epoch in range(start_epoch, end_epoch + 1):\n",
        "    model.train()\n",
        "    running_loss = 0.0\n",
        "\n",
        "    for inp, lbl, inp_mask, _, _, _, _, _ in train_loader:\n",
        "        inp, lbl = inp.to(device), lbl.to(device)\n",
        "        inp_mask = inp_mask.to(device)\n",
        "\n",
        "        sz = inp.size(1)\n",
        "        causal_mask = model.generate_square_subsequent_mask(sz, device)\n",
        "\n",
        "        optimizer.zero_grad()\n",
        "        logits = model(inp, padding_mask=inp_mask, causal_mask=causal_mask)\n",
        "\n",
        "        loss = criterion(logits.reshape(-1, VOCAB_SIZE), lbl.reshape(-1))\n",
        "        loss.backward()\n",
        "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
        "        optimizer.step()\n",
        "\n",
        "        running_loss += loss.item() * inp.size(0)\n",
        "\n",
        "    train_loss = running_loss / len(train_loader.dataset)\n",
        "    history['train_loss'].append(train_loss)\n",
        "\n",
        "    # Validation executed strictly every validate_every epochs (or on final epoch of run)\n",
        "    if epoch % config[\"validate_every\"] == 0 or epoch == end_epoch:\n",
        "        val_loss, val_tf_acc, val_exact_match, val_path_validity = evaluate_model(\n",
        "            model, val_loader, device, run_rollout=True\n",
        "        )\n",
        "        history['val_epochs'].append(epoch)\n",
        "        history['val_loss'].append(val_loss)\n",
        "        history['val_tf_acc'].append(val_tf_acc)\n",
        "        history['val_exact_match'].append(val_exact_match)\n",
        "        history['val_path_validity'].append(val_path_validity)\n",
        "\n",
        "        print(f\"Epoch {epoch:04d}/{config['total_epochs']:04d} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | \"\n",
        "              f\"Val TF Acc: {val_tf_acc:.2f}% | Rollout Exact Match: {val_exact_match:.2f}% | \"\n",
        "              f\"Path Validity: {val_path_validity:.2f}%\")\n",
        "    elif epoch < config[\"validate_every\"]:\n",
        "        if epoch % 5 == 0 or epoch == start_epoch:\n",
        "            print(f\"Epoch {epoch:04d}/{config['total_epochs']:04d} | Train Loss: {train_loss:.4f} | (Validation skipped for this epoch)\")\n",
        "\n",
        "    # Save checkpoint every save_every epochs (or on final epoch)\n",
        "    if epoch % config[\"save_every\"] == 0 or epoch == end_epoch:\n",
        "        checkpoint_payload = {\n",
        "            'epoch': epoch,\n",
        "            'model_state_dict': model.state_dict(),\n",
        "            'optimizer_state_dict': optimizer.state_dict(),\n",
        "            'config': config,\n",
        "            'history': history\n",
        "        }\n",
        "        torch.save(checkpoint_payload, latest_ckpt_path)\n",
        "        if epoch % config[\"save_every\"] == 0:\n",
        "            versioned_path = os.path.join(CKPT_DIR, f\"decoder_only_ar_graph_transformer_epoch_{epoch}.pt\")\n",
        "            torch.save(checkpoint_payload, versioned_path)\n",
        "            print(f\"Saved versioned checkpoint: '{versioned_path}'\")\n",
        "\n",
        "total_train_time = time.time() - start_train_time\n",
        "print(f\"\\nDecoder-Only Training chunk complete in {total_train_time:.2f} seconds.\")\n"
    ]
})

# Cell 6 Header: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_6_md"},
    "source": [
        "### Held-Out Test Set Evaluation\n",
        "We evaluate the Decoder-Only model on the unseen test dataset ($30 \\le K \\le 50$, $10 \\le M \\le 20$).\n"
    ]
})

# Cell 6: Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_6",
    "metadata": {"id": "cell_6"},
    "outputs": [],
    "source": [
        "# Cell 6: Test Set Benchmark\n",
        "\n",
        "test_loss, test_tf_acc, test_exact_match, test_path_validity = evaluate_model(\n",
        "    model, test_loader, device, run_rollout=True\n",
        ")\n",
        "\n",
        "print(\"=\" * 65)\n",
        "print(\"    HELD-OUT TEST SET EVALUATION SUMMARY (DECODER-ONLY)\")\n",
        "print(\"=\" * 65)\n",
        "print(f\"{'Evaluation Metric':<35} | {'Model Score':<15}\")\n",
        "print(\"-\" * 65)\n",
        "print(f\"{'Test Cross-Entropy Loss':<35} | {test_loss:<15.4f}\")\n",
        "print(f\"{'Teacher-Forcing Token Acc (%)':<35} | {test_tf_acc:<15.2f}%\")\n",
        "print(f\"{'Autoregressive Exact Match (%)':<35} | {test_exact_match:<15.2f}%\")\n",
        "print(f\"{'Path Connectivity Validity (%)':<35} | {test_path_validity:<15.2f}%\")\n",
        "print(\"=\" * 65)\n"
    ]
})

# Cell 7 Header: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_7_md"},
    "source": [
        "### Publication-Quality Visualizations & Sample Analysis\n",
        "Generates:\n",
        "1. **Training & Validation Loss Curves** (`charts/decoder_only_ar_graph_dfs_training_curves.png`).\n",
        "2. **Sample Graph Shortest Path Rollout**: Includes the **original input sequence both in text format and in the visual chart layout**, alongside true vs. predicted path overlays and node backtrace counts (`charts/decoder_only_ar_graph_dfs_sample_visualization.png`).\n"
    ]
})

# Cell 7: Code
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_7",
    "metadata": {"id": "cell_7"},
    "outputs": [],
    "source": [
        "# Cell 7: Generate Analytical Figures and Visual Layouts\n",
        "\n",
        "sns.set_theme(style=\"whitegrid\", palette=\"mako\")\n",
        "\n",
        "# Chart 1: Training Trajectories\n",
        "fig, ax1 = plt.subplots(figsize=(10, 5))\n",
        "\n",
        "color = 'tab:blue'\n",
        "ax1.set_xlabel('Epochs', fontsize=12, fontweight='bold')\n",
        "ax1.set_ylabel('Cross-Entropy Loss', color=color, fontsize=12, fontweight='bold')\n",
        "epochs_range = range(1, len(history['train_loss']) + 1)\n",
        "l1 = ax1.plot(epochs_range, history['train_loss'], label='Train Loss', color='navy', linewidth=2, linestyle='--')\n",
        "if history['val_epochs']:\n",
        "    l2 = ax1.plot(history['val_epochs'], history['val_loss'], label='Val Loss', color='royalblue', linewidth=2)\n",
        "else:\n",
        "    l2 = []\n",
        "ax1.tick_params(axis='y', labelcolor=color)\n",
        "\n",
        "ax2 = ax1.twinx()\n",
        "color = 'tab:green'\n",
        "ax2.set_ylabel('Validation Accuracy (%)', color=color, fontsize=12, fontweight='bold')\n",
        "if history['val_epochs']:\n",
        "    l3 = ax2.plot(history['val_epochs'], history['val_tf_acc'], label='Val TF Token Acc (%)', color='forestgreen', linewidth=2)\n",
        "    l4 = ax2.plot(history['val_epochs'], history['val_exact_match'], label='Rollout Exact Match (%)', color='darkgreen', linewidth=2, linestyle=':')\n",
        "    lines = l1 + l2 + l3 + l4\n",
        "else:\n",
        "    lines = l1\n",
        "labels = [l.get_label() for l in lines]\n",
        "ax1.legend(lines, labels, loc='center right', frameon=True, facecolor='white', framealpha=0.9)\n",
        "\n",
        "plt.title('Decoder-Only Autoregressive Graph Transformer: Training Trajectories', fontsize=14, fontweight='bold', pad=15)\n",
        "plt.tight_layout()\n",
        "if os.path.basename(os.getcwd()) == \"graphs\":\n",
        "    plt.savefig(\"../charts/decoder_only_ar_graph_dfs_training_curves.png\", dpi=300, bbox_inches='tight')\n",
        "    plt.savefig(\"charts/decoder_only_ar_graph_dfs_training_curves.png\", dpi=300, bbox_inches='tight')\n",
        "else:\n",
        "    plt.savefig(\"charts/decoder_only_ar_graph_dfs_training_curves.png\", dpi=300, bbox_inches='tight')\n",
        "    plt.savefig(\"graphs/charts/decoder_only_ar_graph_dfs_training_curves.png\", dpi=300, bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "# Chart 2: Sample Graph Shortest Path Rollout with Original Sequence Text and Visual Layout\n",
        "sample_inp, sample_lbl, sample_mask, sample_trace, sample_sp, G_sample, backtracks_sample, node_backtraces_sample = test_dataset[0]\n",
        "\n",
        "model.eval()\n",
        "with torch.no_grad():\n",
        "    pred_rollout = model.solve_graph_autoregressive([sample_trace], device=device)[0]\n",
        "\n",
        "plt.figure(figsize=(10, 7))\n",
        "pos = nx.spring_layout(G_sample, seed=42)\n",
        "\n",
        "# Draw base graph\n",
        "nx.draw_networkx_nodes(G_sample, pos, node_color='lightgray', node_size=550)\n",
        "nx.draw_networkx_edges(G_sample, pos, edge_color='silver', width=1.5)\n",
        "\n",
        "# Highlight Shortest Path Edges\n",
        "sp_edges = [(sample_sp[i], sample_sp[i+1]) for i in range(len(sample_sp)-1)]\n",
        "nx.draw_networkx_edges(G_sample, pos, edgelist=sp_edges, edge_color='#2b5c8f', width=3.5, label='True Shortest Path')\n",
        "\n",
        "# Highlight Start and Destination Nodes\n",
        "nx.draw_networkx_nodes(G_sample, pos, nodelist=[sample_sp[0]], node_color='limegreen', node_size=750, label='Start Node')\n",
        "nx.draw_networkx_nodes(G_sample, pos, nodelist=[sample_sp[-1]], node_color='crimson', node_size=750, label='Goal Node')\n",
        "\n",
        "labels = {node: str(node) for node in G_sample.nodes()}\n",
        "nx.draw_networkx_labels(G_sample, pos, labels=labels, font_size=9, font_weight='bold')\n",
        "\n",
        "# Formatted original sequence text block\n",
        "trace_str = f\"Original Input DFS Trace (K={len(sample_trace)}):\\n\" + \", \".join(map(str, sample_trace[:25])) + \"\\n\" + \", \".join(map(str, sample_trace[25:]))\n",
        "sp_str = f\"Target Shortest Path (M={len(sample_sp)}): {sample_sp}\"\n",
        "pred_str = f\"Decoder-Only Autoregressive Predicted Path: {pred_rollout}\"\n",
        "backtrack_str = f\"Total Backtracks: {backtracks_sample} | Node Regressions: {dict(list(node_backtraces_sample.items())[:5])}\"\n",
        "\n",
        "plt.gcf().text(0.12, 0.02, f\"{trace_str}\\n{sp_str}\\n{pred_str}\\n{backtrack_str}\",\n",
        "               fontsize=9, bbox=dict(boxstyle='round,pad=0.5', facecolor='white', alpha=0.9, edgecolor='gray'))\n",
        "\n",
        "plt.title(\"Decoder-Only Autoregressive Shortest Path Prediction Layout\", fontsize=13, fontweight='bold', pad=15)\n",
        "plt.legend(scatterpoints=1, loc='upper left', frameon=True, facecolor='white')\n",
        "plt.axis('off')\n",
        "plt.tight_layout()\n",
        "plt.subplots_adjust(bottom=0.25)\n",
        "\n",
        "if os.path.basename(os.getcwd()) == \"graphs\":\n",
        "    plt.savefig(\"../charts/decoder_only_ar_graph_dfs_sample_visualization.png\", dpi=300, bbox_inches='tight')\n",
        "    plt.savefig(\"charts/decoder_only_ar_graph_dfs_sample_visualization.png\", dpi=300, bbox_inches='tight')\n",
        "else:\n",
        "    plt.savefig(\"charts/decoder_only_ar_graph_dfs_sample_visualization.png\", dpi=300, bbox_inches='tight')\n",
        "    plt.savefig(\"graphs/charts/decoder_only_ar_graph_dfs_sample_visualization.png\", dpi=300, bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "print(\"Publication-quality figures generated and saved.\")\n"
    ]
})

# Cell 8: Self-Reflection Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {"id": "cell_8_md"},
    "source": [
        "### Self-Reflection & Mechanics of Good vs. Bad Plans in Decoder-Only LLMs\n",
        "\n",
        "1. **Decoder-Only vs. Encoder-Decoder Architectural Shift**:\n",
        "   Transitioning from an Encoder-Decoder model to a Decoder-Only model eliminates cross-attention layers. Instead, the model relies on causal self-attention over the concatenated trace prompt and path tokens. Causal self-attention forces every position in the target sequence to attend directly to relevant forward and exit anchor positions within the 1D DFS trace prompt.\n",
        "2. **Target Path Loss Masking Mechanics**:\n",
        "   Because the model processes the concatenated prompt sequence $[t_1, \\dots, t_K, p_1, \\dots, p_M]$, computing loss over the prompt tokens ($t_1 \\dots t_{K-1}$) would waste capacity on language modeling of the input DFS trace. By setting `ignore_index = PAD_TOKEN` for positions $0 \\dots K-2$, 100% of the gradient signal is dedicated to predicting path rollout tokens $p_1 \\dots p_M$.\n",
        "3. **Mechanics of a Good Plan vs. a Bad Plan**:\n",
        "   - **Good Plan**: The causal decoder attends to key forward branch points and exit anchors in the trace prompt, outputting valid adjacent graph transitions $(p_{m-1}, p_m) \\in E_G$ until destination $g$ is reached.\n",
        "   - **Bad Plan & Compounding Errors**: In long target sequences ($M \\in [10, 20]$), an early prediction error shifts the causal context into out-of-distribution space. Compounding error scaling ($1 - (1 - \\epsilon)^M$) leads to sequence failure or infinite loop generation.\n"
    ]
})

nb_content = {
    "cells": cells,
    "metadata": {
        "colab": {"provenance": []},
        "language_info": {"name": "python"},
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

target_dir = "src/3.DecoderOnly"
target_path = os.path.join(target_dir, "1.Small_Easy_DecoderOnly_Autoregressive_GSP.ipynb")
os.makedirs(target_dir, exist_ok=True)
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(nb_content, f, indent=2)

print(f"Successfully generated notebook '{target_path}'. Total cells: {len(cells)}")
